/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package principal;

/**
 *
 * @author Fer Landa San
 */
public class FrmAyuda extends javax.swing.JFrame {

    /**
     * Creates new form FrmAyuda
     */
    public FrmAyuda() {
        initComponents();
        this.setTitle("Ayuda del Lenguaje");
    this.setLocationRelativeTo(null); // Centrar ventana
    
    // Contenido de la ayuda
    String ayuda = "";
    ayuda += "=== TIPOS DE DATOS ===\n";
    ayuda += "  int, double, string, boolean\n\n";
    
    ayuda += "=== ESTRUCTURA PRINCIPAL ===\n";
    ayuda += "  int main() {\n";
    ayuda += "      // Tu codigo aqui\n";
    ayuda += "  }\n\n";
    
    ayuda += "=== OPERACIONES Y MATEMÁTICAS ===\n";
    ayuda += "  Aritmética: +, -, *, /, ** (potencia)\n";
    ayuda += "  Unarios:    x++, x--\n";
    ayuda += "  Relacional: ==, !=, <, >, <=, >=\n";
    ayuda += "  Funciones:  sqrt(x), sin(x), cos(x), factorial(n)\n\n";
    
    ayuda += "=== ALGORITMOS ESPECIALES ===\n";
    ayuda += "  fibonacci(n)       -> Calcula el n-ésimo número\n";
    ayuda += "  formula_general(a,b,c) -> Resuelve ax^2 + bx + c\n\n";
    
    ayuda += "=== CONTROL DE FLUJO ===\n";
    ayuda += "  if (condicion) { ... }\n";
    ayuda += "  while (condicion) do { ... } fin while\n";
    ayuda += "  // Nota: Los bloques deben usar llaves { }\n";
    
    txtAyuda.setText(ayuda);
    txtAyuda.setCaretPosition(0); // Scroll al inicio
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtAyuda = new javax.swing.JTextArea();
        jLabelTitulo = new javax.swing.JLabel();
        btnCerr = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtAyuda.setEditable(false);
        txtAyuda.setColumns(20);
        txtAyuda.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        txtAyuda.setRows(5);
        jScrollPane1.setViewportView(txtAyuda);

        jLabelTitulo.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("Guía de Referencia");
        jLabelTitulo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 204), 4, true));
        jLabelTitulo.setOpaque(true);

        btnCerr.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        btnCerr.setText("Cerrar");
        btnCerr.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 255, 204), 4, true));
        btnCerr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCerr, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(btnCerr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrActionPerformed

       this.dispose();
       
    }//GEN-LAST:event_btnCerrActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAyuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAyuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAyuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAyuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAyuda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerr;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtAyuda;
    // End of variables declaration//GEN-END:variables
}
