/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package principal;

import codigo.Lexer;
import codigo.Sintax;
import codigo.TablaSimbolos;
import codigo.Simbolo;
import codigo.GestorTripletas;
import codigo.Tripleta;
import java.awt.Color;
import java.io.StringReader;
import java_cup.runtime.Symbol;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author SkullCandy
 */
public class FrmPrincipal extends javax.swing.JFrame {

    ImagenFondo fondo = new ImagenFondo();
    private JTable tablaTokens;
    private JTable tablaTripletas;
    private JTable tablaPolaca;
    private JTable tablaSimbolos;
    private DefaultTableModel modeloTokens;
    private DefaultTableModel modeloTripletas;
    private DefaultTableModel modeloPolaca;
    private DefaultTableModel modeloSimbolos;

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        this.setContentPane(fondo);
        initComponents();

        setLocationRelativeTo(null);
        inicializarTablas();

    }

    private void inicializarTablas() {
        // Crear modelos de tabla
        modeloTokens = new DefaultTableModel(new String[]{"TOKEN", "LEXEMA"}, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        modeloTripletas = new DefaultTableModel(new String[]{"TEMP", "ARG1", "OPERADOR", "ARG2"}, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        modeloPolaca = new DefaultTableModel(new String[]{"ARG1", "ARG2", "OPERADOR"}, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        modeloSimbolos = new DefaultTableModel(new String[]{"VARIABLE", "TIPO", "VALOR"}, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        // Crear JTables
        tablaTokens = new JTable(modeloTokens);
        tablaTripletas = new JTable(modeloTripletas);
        tablaPolaca = new JTable(modeloPolaca);
        tablaSimbolos = new JTable(modeloSimbolos);

        // Configurar apariencia de las tablas
        configurarTabla(tablaTokens);
        configurarTabla(tablaTripletas);
        configurarTabla(tablaPolaca);
        configurarTabla(tablaSimbolos);

        // Crear panel con pestañas
        JTabbedPane tabbedPane = new JTabbedPane();
        tabbedPane.addTab("Tokens", new JScrollPane(tablaTokens));
        tabbedPane.addTab("Tripletas", new JScrollPane(tablaTripletas));
        tabbedPane.addTab("Notación Polaca", new JScrollPane(tablaPolaca));
        tabbedPane.addTab("Símbolos", new JScrollPane(tablaSimbolos));

        // Reemplazar jScrollPane2 con el TabbedPane
        jScrollPane2.setViewportView(tabbedPane);
    }

    private void configurarTabla(JTable tabla) {
        tabla.setFont(new Font("Monospaced", Font.PLAIN, 12));
        tabla.getTableHeader().setFont(new Font("Monospaced", Font.BOLD, 12));
        tabla.getTableHeader().setBackground(new Color(70, 130, 180));
        tabla.getTableHeader().setForeground(Color.BLACK);
        tabla.setRowHeight(25);
        tabla.setShowGrid(true);
        tabla.setGridColor(Color.LIGHT_GRAY);
    }

    private void limpiarTablas() {
        modeloTokens.setRowCount(0);
        modeloTripletas.setRowCount(0);
        modeloPolaca.setRowCount(0);
        modeloSimbolos.setRowCount(0);
    }

    private String getNombreToken(int sym) {
        String[] nombres = codigo.sym.terminalNames;
        if (sym >= 0 && sym < nombres.length) {
            return nombres[sym];
        }
        return "UNKNOWN";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtEntrada = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtResultado = new javax.swing.JTextArea();
        btnAnalizar = new javax.swing.JButton();
        jLabelTitulo = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();
        jLabelTitulo1 = new javax.swing.JLabel();
        btnSeno = new javax.swing.JButton();
        btnFibonacci = new javax.swing.JButton();
        btnForm = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemAbrir = new javax.swing.JMenuItem();
        jMenuItemGuardar = new javax.swing.JMenuItem();
        jMenuItemCerrar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemLex = new javax.swing.JMenuItem();
        jMenuItemCreditos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImages(null);

        txtEntrada.setColumns(20);
        txtEntrada.setRows(5);
        txtEntrada.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 3, true));
        jScrollPane1.setViewportView(txtEntrada);

        txtResultado.setColumns(20);
        txtResultado.setRows(5);
        jScrollPane2.setViewportView(txtResultado);

        btnAnalizar.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        btnAnalizar.setText("Compilar");
        btnAnalizar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 255, 204), 4, true));
        btnAnalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalizarActionPerformed(evt);
            }
        });

        jLabelTitulo.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("COMPILERMAX");
        jLabelTitulo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 204), 4, true));
        jLabelTitulo.setOpaque(true);

        btnLimpiar.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 153), 4, true));
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        jLabelTitulo1.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTitulo1.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        jLabelTitulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo1.setText("Codigo:");
        jLabelTitulo1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 204), 4, true));
        jLabelTitulo1.setOpaque(true);

        btnSeno.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        btnSeno.setText("Seno");
        btnSeno.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 153), 4, true));
        btnSeno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSenoActionPerformed(evt);
            }
        });

        btnFibonacci.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        btnFibonacci.setText("Fibonacci");
        btnFibonacci.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 153), 4, true));
        btnFibonacci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFibonacciActionPerformed(evt);
            }
        });

        btnForm.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        btnForm.setText("Form.Gen");
        btnForm.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 153), 4, true));
        btnForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/emoji3.jpg"))); // NOI18N
        jLabel1.setOpaque(true);

        jMenu1.setText("Archivo");

        jMenuItemAbrir.setText("Abrir");
        jMenuItemAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAbrirActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemAbrir);

        jMenuItemGuardar.setText("Guardar");
        jMenuItemGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGuardarActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemGuardar);

        jMenuItemCerrar.setText("Cerrar");
        jMenuItemCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCerrarActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemCerrar);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ayuda");

        jMenuItemLex.setText("Lexico");
        jMenuItemLex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLexActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemLex);

        jMenuItemCreditos.setText("Creditos");
        jMenuItemCreditos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCreditosActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemCreditos);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelTitulo1)
                                .addGap(209, 209, 209)
                                .addComponent(jLabelTitulo)
                                .addGap(227, 227, 227)
                                .addComponent(jLabel1))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 788, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 31, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAnalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSeno, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnFibonacci, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnForm, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(31, 31, 31))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelTitulo1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAnalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSeno, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnFibonacci, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnForm, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalizarActionPerformed

        Sintax.tabla = new TablaSimbolos();
        Sintax.gestor = new GestorTripletas();
        Sintax.gestor.limpiar();

        String entrada = txtEntrada.getText();
        Symbol s = null;

        try {
            // Primera pasada: capturar tokens
            Lexer lexer = new Lexer(new StringReader(entrada));

            while (true) {
                Symbol token = lexer.next_token();
                if (token.sym == 0) {
                    break;
                }

                String nombreToken = getNombreToken(token.sym);
                String lexema = (token.value != null) ? token.value.toString() : "";
                modeloTokens.addRow(new Object[]{nombreToken, lexema});
            }

            // Segunda pasada: análisis sintáctico y semántico
            Lexer lexerParaParser = new Lexer(new StringReader(entrada));
            Sintax sinta = new Sintax(lexerParaParser);

            try {
                sinta.parse();

                // Llenar tabla de símbolos
                for (Simbolo sim : Sintax.tabla.t.values()) {
                    String valor = (sim.valor != null) ? sim.valor.toString() : "null";
                    modeloSimbolos.addRow(new Object[]{sim.nombre, sim.tipo, valor});
                }

                // Llenar tabla de tripletas
                for (Tripleta t : Sintax.gestor.getTripletas()) {
                    String arg1 = t.getOperando1();
                    String operador = t.getOperador();
                    String arg2 = t.getOperando2();
                    String temp = t.getResultado();

                    modeloTripletas.addRow(new Object[]{temp, arg1, operador, arg2});

                    // Llenar tabla de notación polaca
                    if (operador.equals("=")) {
                        modeloPolaca.addRow(new Object[]{arg1, temp, operador});
                    } else if (arg2.equals("-")) {
                        // Operación unaria
                        modeloPolaca.addRow(new Object[]{arg1, "-", operador});
                    } else if (operador.equals("DECL")) {
                        modeloPolaca.addRow(new Object[]{"DECL", arg1, temp});
                    } else {
                        // Operación binaria
                        modeloPolaca.addRow(new Object[]{arg1, arg2, operador});
                    }
                }

                JOptionPane.showMessageDialog(this,
                        "✓ COMPILACIÓN EXITOSA\n\n"
                        + "✓ Sintaxis correcta\n"
                        + "✓ Semántica correcta",
                        "Éxito",
                        JOptionPane.INFORMATION_MESSAGE);

            } catch (Exception ex) {
                s = sinta.getS();
                JOptionPane.showMessageDialog(this,
                        "✗ ERROR DE SINTAXIS\n\n"
                        + "Línea: " + (s.right + 1) + "\n"
                        + "Columna: " + (s.left + 1) + "\n"
                        + "Token: " + s.value,
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAnalizarActionPerformed

    private void jMenuItemAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAbrirActionPerformed
        // TODO add your handling code here:

        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Abrir código fuente");

        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Codigo Fuente (*.txt, *.cmx)", "txt", "cmx");
        fileChooser.setFileFilter(filtro);

        int resultado = fileChooser.showOpenDialog(this);

        if (resultado == JFileChooser.APPROVE_OPTION) {

            File archivoSeleccionado = fileChooser.getSelectedFile();
            String nombreArchivo = archivoSeleccionado.getName().toLowerCase();

            if (nombreArchivo.endsWith(".txt") || nombreArchivo.endsWith(".cmx")) {

                try {

                    FileReader reader = new FileReader(archivoSeleccionado);
                    BufferedReader br = new BufferedReader(reader);

                    String linea;
                    StringBuilder contenido = new StringBuilder();

                    while ((linea = br.readLine()) != null) {
                        contenido.append(linea).append("\n");
                    }
                    br.close();
                    reader.close();

                    txtEntrada.setText(contenido.toString());
                    
                    limpiarTablas();
                } catch (IOException e) {
                    JOptionPane.showMessageDialog(this, "Error al leer el archivo: " + e.getMessage());
                }

            } else {

                JOptionPane.showMessageDialog(this, "Tipo incorrecto. Por favor seleccione un archivo .txt o .cmx", "Error de Archivo", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jMenuItemAbrirActionPerformed

    private void jMenuItemGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGuardarActionPerformed
        // TODO add your handling code here:

        try {

            JFileChooser fileChooser = new JFileChooser();
            fileChooser.setDialogTitle("Guardar archivo como...");

            FileNameExtensionFilter filtro = new FileNameExtensionFilter("Código Fuente CompilerM (*.cmx)", "cmx");
            fileChooser.setFileFilter(filtro);

            int seleccion = fileChooser.showSaveDialog(this);

            if (seleccion == JFileChooser.APPROVE_OPTION) {
                File archivo = fileChooser.getSelectedFile();
                String nombre = archivo.getName();

                if (!nombre.toLowerCase().endsWith(".cmx") && !nombre.toLowerCase().endsWith(".txt")) {
                    archivo = new File(archivo.getAbsolutePath() + ".cmx");
                }

                FileWriter fw = new FileWriter(archivo);
                BufferedWriter bw = new BufferedWriter(fw);

                bw.write(txtEntrada.getText());
                bw.close();

                JOptionPane.showMessageDialog(this, "Archivo guardado exitosamente.");

            }

        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error al guardar el archivo: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItemGuardarActionPerformed

    private void jMenuItemCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCerrarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jMenuItemCerrarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:

        txtEntrada.setText("");
        limpiarTablas();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnSenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSenoActionPerformed
        // TODO add your handling code here:
        txtEntrada.setText("");
        limpiarTablas();
        txtEntrada.setText("int main() {\n"
                + "double seno = sin(1.57);\n"
                + "}");
    }//GEN-LAST:event_btnSenoActionPerformed

    private void btnFibonacciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFibonacciActionPerformed
        // TODO add your handling code here:

        txtEntrada.setText("");
        limpiarTablas();
        txtEntrada.setText("int main() {\n"
                + "    int x = fibonacci(3);\n"
                + "}");
    }//GEN-LAST:event_btnFibonacciActionPerformed

    private void btnFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormActionPerformed
        // TODO add your handling code here:

        txtEntrada.setText("");
        limpiarTablas();
        txtEntrada.setText("int main() {\n"
                + "    double formula = formula_general(1, 7, 12);\n"
                + "}");

    }//GEN-LAST:event_btnFormActionPerformed

    private void jMenuItemLexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLexActionPerformed
        // TODO add your handling code here:
        FrmAyuda ventanaAyuda = new FrmAyuda();
        ventanaAyuda.setVisible(true);

    }//GEN-LAST:event_jMenuItemLexActionPerformed

    private void jMenuItemCreditosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCreditosActionPerformed
        // TODO add your handling code here:

        JPanel panelCreditos = new JPanel();
        panelCreditos.setLayout(new BoxLayout(panelCreditos, BoxLayout.Y_AXIS));

        JLabel labelTitulo = new JLabel("CompilerMax v1.0");
        JLabel labelAutor = new JLabel("Desarrollado por: ");
        JLabel labelContacto1 = new JLabel("Marco Fernando Silva Rodriguez");
        JLabel labelContacto2 = new JLabel("Luis Gael Fernández Dávalos");
        JLabel labelContacto3 = new JLabel("Ximena Arciniega Ochoa");
        JLabel labelContacto4 = new JLabel("Miguel Angel Irungaray Reyna");

        labelTitulo.setAlignmentX(Component.CENTER_ALIGNMENT);
        labelTitulo.setFont(new Font("Arial", Font.BOLD, 14));

        labelAutor.setAlignmentX(Component.CENTER_ALIGNMENT);
        labelContacto1.setAlignmentX(Component.CENTER_ALIGNMENT);
        labelContacto2.setAlignmentX(Component.CENTER_ALIGNMENT);
        labelContacto3.setAlignmentX(Component.CENTER_ALIGNMENT);
        labelContacto4.setAlignmentX(Component.CENTER_ALIGNMENT);

        panelCreditos.add(labelTitulo);
        panelCreditos.add(Box.createVerticalStrut(10));
        panelCreditos.add(labelAutor);
        panelCreditos.add(labelContacto1);
        panelCreditos.add(labelContacto2);
        panelCreditos.add(labelContacto3);
        panelCreditos.add(labelContacto4);

        JOptionPane.showMessageDialog(null, panelCreditos, "Créditos", JOptionPane.PLAIN_MESSAGE);


    }//GEN-LAST:event_jMenuItemCreditosActionPerformed

    public class ImagenFondo extends JPanel {

        private Image imagen;

        @Override
        public void paint(Graphics g) {
            imagen = new ImageIcon(getClass().getResource("/Imagenes/Imagen3.jpg")).getImage();

            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);

            setOpaque(false);

            super.paint(g);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnalizar;
    private javax.swing.JButton btnFibonacci;
    private javax.swing.JButton btnForm;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnSeno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelTitulo1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemAbrir;
    private javax.swing.JMenuItem jMenuItemCerrar;
    private javax.swing.JMenuItem jMenuItemCreditos;
    private javax.swing.JMenuItem jMenuItemGuardar;
    private javax.swing.JMenuItem jMenuItemLex;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtEntrada;
    private javax.swing.JTextArea txtResultado;
    // End of variables declaration//GEN-END:variables
}
