
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

package codigo;

import java_cup.runtime.Symbol;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20150326 (SVN rev 63) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class Sintax extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public Sintax() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public Sintax(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Sintax(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\050\000\002\002\004\000\002\002\011\000\002\003" +
    "\004\000\002\003\003\000\002\007\003\000\002\007\003" +
    "\000\002\007\003\000\002\007\003\000\002\004\005\000" +
    "\002\004\007\000\002\004\006\000\002\004\005\000\002" +
    "\004\005\000\002\004\011\000\002\004\011\000\002\006" +
    "\005\000\002\006\005\000\002\006\005\000\002\006\005" +
    "\000\002\006\003\000\002\006\003\000\002\006\003\000" +
    "\002\005\005\000\002\005\005\000\002\005\005\000\002" +
    "\005\005\000\002\005\005\000\002\005\006\000\002\005" +
    "\006\000\002\005\006\000\002\005\006\000\002\005\006" +
    "\000\002\005\012\000\002\005\003\000\002\005\003\000" +
    "\002\005\003\000\002\005\003\000\002\005\003\000\002" +
    "\005\003\000\002\005\005" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\147\000\004\004\005\001\002\000\004\002\151\001" +
    "\002\000\004\014\006\001\002\000\004\022\007\001\002" +
    "\000\004\023\010\001\002\000\004\024\011\001\002\000" +
    "\020\004\020\005\023\006\016\007\017\010\012\012\013" +
    "\026\022\001\002\000\004\022\143\001\002\000\004\022" +
    "\121\001\002\000\022\004\ufffe\005\ufffe\006\ufffe\007\ufffe" +
    "\010\ufffe\012\ufffe\025\ufffe\026\ufffe\001\002\000\004\026" +
    "\114\001\002\000\004\026\ufffb\001\002\000\004\026\ufffa" +
    "\001\002\000\004\026\ufffd\001\002\000\022\004\020\005" +
    "\023\006\016\007\017\010\012\012\013\025\113\026\022" +
    "\001\002\000\010\017\026\041\024\042\025\001\002\000" +
    "\004\026\ufffc\001\002\000\004\016\111\001\002\000\004" +
    "\016\110\001\002\000\034\022\034\026\037\027\042\030" +
    "\035\031\032\032\041\033\036\051\030\052\040\053\044" +
    "\055\031\056\033\057\027\001\002\000\004\022\101\001" +
    "\002\000\004\022\076\001\002\000\004\022\073\001\002" +
    "\000\032\016\uffde\021\uffde\023\uffde\034\uffde\035\uffde\036" +
    "\uffde\037\uffde\040\uffde\043\uffde\044\uffde\045\uffde\046\uffde" +
    "\001\002\000\004\022\070\001\002\000\034\022\034\026" +
    "\037\027\042\030\035\031\032\032\041\033\036\051\030" +
    "\052\040\053\044\055\031\056\033\057\027\001\002\000" +
    "\032\016\uffdf\021\uffdf\023\uffdf\034\uffdf\035\uffdf\036\uffdf" +
    "\037\uffdf\040\uffdf\043\uffdf\044\uffdf\045\uffdf\046\uffdf\001" +
    "\002\000\032\016\uffdc\021\uffdc\023\uffdc\034\uffdc\035\uffdc" +
    "\036\uffdc\037\uffdc\040\uffdc\043\uffdc\044\uffdc\045\uffdc\046" +
    "\uffdc\001\002\000\032\016\uffdb\021\uffdb\023\uffdb\034\uffdb" +
    "\035\uffdb\036\uffdb\037\uffdb\040\uffdb\043\uffdb\044\uffdb\045" +
    "\uffdb\046\uffdb\001\002\000\004\022\063\001\002\000\032" +
    "\016\uffdd\021\uffdd\023\uffdd\034\uffdd\035\uffdd\036\uffdd\037" +
    "\uffdd\040\uffdd\043\uffdd\044\uffdd\045\uffdd\046\uffdd\001\002" +
    "\000\032\016\uffe0\021\uffe0\023\uffe0\034\uffe0\035\uffe0\036" +
    "\uffe0\037\uffe0\040\uffe0\043\uffe0\044\uffe0\045\uffe0\046\uffe0" +
    "\001\002\000\016\016\062\034\052\035\051\036\054\037" +
    "\047\040\053\001\002\000\004\022\045\001\002\000\034" +
    "\022\034\026\037\027\042\030\035\031\032\032\041\033" +
    "\036\051\030\052\040\053\044\055\031\056\033\057\027" +
    "\001\002\000\016\023\050\034\052\035\051\036\054\037" +
    "\047\040\053\001\002\000\034\022\034\026\037\027\042" +
    "\030\035\031\032\032\041\033\036\051\030\052\040\053" +
    "\044\055\031\056\033\057\027\001\002\000\032\016\uffe4" +
    "\021\uffe4\023\uffe4\034\uffe4\035\uffe4\036\uffe4\037\uffe4\040" +
    "\uffe4\043\uffe4\044\uffe4\045\uffe4\046\uffe4\001\002\000\034" +
    "\022\034\026\037\027\042\030\035\031\032\032\041\033" +
    "\036\051\030\052\040\053\044\055\031\056\033\057\027" +
    "\001\002\000\034\022\034\026\037\027\042\030\035\031" +
    "\032\032\041\033\036\051\030\052\040\053\044\055\031" +
    "\056\033\057\027\001\002\000\034\022\034\026\037\027" +
    "\042\030\035\031\032\032\041\033\036\051\030\052\040" +
    "\053\044\055\031\056\033\057\027\001\002\000\034\022" +
    "\034\026\037\027\042\030\035\031\032\032\041\033\036" +
    "\051\030\052\040\053\044\055\031\056\033\057\027\001" +
    "\002\000\032\016\uffe9\021\uffe9\023\uffe9\034\uffe9\035\uffe9" +
    "\036\uffe9\037\uffe9\040\053\043\uffe9\044\uffe9\045\uffe9\046" +
    "\uffe9\001\002\000\032\016\uffe7\021\uffe7\023\uffe7\034\uffe7" +
    "\035\uffe7\036\uffe7\037\uffe7\040\053\043\uffe7\044\uffe7\045" +
    "\uffe7\046\uffe7\001\002\000\032\016\uffeb\021\uffeb\023\uffeb" +
    "\034\uffeb\035\uffeb\036\054\037\047\040\053\043\uffeb\044" +
    "\uffeb\045\uffeb\046\uffeb\001\002\000\032\016\uffea\021\uffea" +
    "\023\uffea\034\uffea\035\uffea\036\054\037\047\040\053\043" +
    "\uffea\044\uffea\045\uffea\046\uffea\001\002\000\032\016\uffe8" +
    "\021\uffe8\023\uffe8\034\uffe8\035\uffe8\036\uffe8\037\uffe8\040" +
    "\053\043\uffe8\044\uffe8\045\uffe8\046\uffe8\001\002\000\022" +
    "\004\ufff7\005\ufff7\006\ufff7\007\ufff7\010\ufff7\012\ufff7\025" +
    "\ufff7\026\ufff7\001\002\000\034\022\034\026\037\027\042" +
    "\030\035\031\032\032\041\033\036\051\030\052\040\053" +
    "\044\055\031\056\033\057\027\001\002\000\016\023\065" +
    "\034\052\035\051\036\054\037\047\040\053\001\002\000" +
    "\032\016\uffe5\021\uffe5\023\uffe5\034\uffe5\035\uffe5\036\uffe5" +
    "\037\uffe5\040\uffe5\043\uffe5\044\uffe5\045\uffe5\046\uffe5\001" +
    "\002\000\016\023\067\034\052\035\051\036\054\037\047" +
    "\040\053\001\002\000\032\016\uffda\021\uffda\023\uffda\034" +
    "\uffda\035\uffda\036\uffda\037\uffda\040\uffda\043\uffda\044\uffda" +
    "\045\uffda\046\uffda\001\002\000\034\022\034\026\037\027" +
    "\042\030\035\031\032\032\041\033\036\051\030\052\040" +
    "\053\044\055\031\056\033\057\027\001\002\000\016\023" +
    "\072\034\052\035\051\036\054\037\047\040\053\001\002" +
    "\000\032\016\uffe2\021\uffe2\023\uffe2\034\uffe2\035\uffe2\036" +
    "\uffe2\037\uffe2\040\uffe2\043\uffe2\044\uffe2\045\uffe2\046\uffe2" +
    "\001\002\000\034\022\034\026\037\027\042\030\035\031" +
    "\032\032\041\033\036\051\030\052\040\053\044\055\031" +
    "\056\033\057\027\001\002\000\016\023\075\034\052\035" +
    "\051\036\054\037\047\040\053\001\002\000\032\016\uffe3" +
    "\021\uffe3\023\uffe3\034\uffe3\035\uffe3\036\uffe3\037\uffe3\040" +
    "\uffe3\043\uffe3\044\uffe3\045\uffe3\046\uffe3\001\002\000\034" +
    "\022\034\026\037\027\042\030\035\031\032\032\041\033" +
    "\036\051\030\052\040\053\044\055\031\056\033\057\027" +
    "\001\002\000\016\023\100\034\052\035\051\036\054\037" +
    "\047\040\053\001\002\000\032\016\uffe6\021\uffe6\023\uffe6" +
    "\034\uffe6\035\uffe6\036\uffe6\037\uffe6\040\uffe6\043\uffe6\044" +
    "\uffe6\045\uffe6\046\uffe6\001\002\000\034\022\034\026\037" +
    "\027\042\030\035\031\032\032\041\033\036\051\030\052" +
    "\040\053\044\055\031\056\033\057\027\001\002\000\016" +
    "\021\103\034\052\035\051\036\054\037\047\040\053\001" +
    "\002\000\034\022\034\026\037\027\042\030\035\031\032" +
    "\032\041\033\036\051\030\052\040\053\044\055\031\056" +
    "\033\057\027\001\002\000\016\021\105\034\052\035\051" +
    "\036\054\037\047\040\053\001\002\000\034\022\034\026" +
    "\037\027\042\030\035\031\032\032\041\033\036\051\030" +
    "\052\040\053\044\055\031\056\033\057\027\001\002\000" +
    "\016\023\107\034\052\035\051\036\054\037\047\040\053" +
    "\001\002\000\032\016\uffe1\021\uffe1\023\uffe1\034\uffe1\035" +
    "\uffe1\036\uffe1\037\uffe1\040\uffe1\043\uffe1\044\uffe1\045\uffe1" +
    "\046\uffe1\001\002\000\022\004\ufff5\005\ufff5\006\ufff5\007" +
    "\ufff5\010\ufff5\012\ufff5\025\ufff5\026\ufff5\001\002\000\022" +
    "\004\ufff6\005\ufff6\006\ufff6\007\ufff6\010\ufff6\012\ufff6\025" +
    "\ufff6\026\ufff6\001\002\000\022\004\uffff\005\uffff\006\uffff" +
    "\007\uffff\010\uffff\012\uffff\025\uffff\026\uffff\001\002\000" +
    "\004\002\000\001\002\000\006\016\115\017\116\001\002" +
    "\000\022\004\ufff9\005\ufff9\006\ufff9\007\ufff9\010\ufff9\012" +
    "\ufff9\025\ufff9\026\ufff9\001\002\000\034\022\034\026\037" +
    "\027\042\030\035\031\032\032\041\033\036\051\030\052" +
    "\040\053\044\055\031\056\033\057\027\001\002\000\016" +
    "\016\120\034\052\035\051\036\054\037\047\040\053\001" +
    "\002\000\022\004\ufff8\005\ufff8\006\ufff8\007\ufff8\010\ufff8" +
    "\012\ufff8\025\ufff8\026\ufff8\001\002\000\034\022\034\026" +
    "\122\027\042\030\035\031\032\032\124\033\123\051\030" +
    "\052\040\053\044\055\031\056\033\057\027\001\002\000" +
    "\026\023\uffec\034\uffdb\035\uffdb\036\uffdb\037\uffdb\040\uffdb" +
    "\043\uffdb\044\uffdb\045\uffdb\046\uffdb\001\002\000\026\023" +
    "\uffed\034\uffdc\035\uffdc\036\uffdc\037\uffdc\040\uffdc\043\uffdc" +
    "\044\uffdc\045\uffdc\046\uffdc\001\002\000\026\023\uffee\034" +
    "\uffdd\035\uffdd\036\uffdd\037\uffdd\040\uffdd\043\uffdd\044\uffdd" +
    "\045\uffdd\046\uffdd\001\002\000\024\034\052\035\051\036" +
    "\054\037\047\040\053\043\133\044\136\045\134\046\135" +
    "\001\002\000\004\023\127\001\002\000\004\024\130\001" +
    "\002\000\020\004\020\005\023\006\016\007\017\010\012" +
    "\012\013\026\022\001\002\000\022\004\020\005\023\006" +
    "\016\007\017\010\012\012\013\025\132\026\022\001\002" +
    "\000\022\004\ufff3\005\ufff3\006\ufff3\007\ufff3\010\ufff3\012" +
    "\ufff3\025\ufff3\026\ufff3\001\002\000\034\022\034\026\037" +
    "\027\042\030\035\031\032\032\041\033\036\051\030\052" +
    "\040\053\044\055\031\056\033\057\027\001\002\000\034" +
    "\022\034\026\037\027\042\030\035\031\032\032\041\033" +
    "\036\051\030\052\040\053\044\055\031\056\033\057\027" +
    "\001\002\000\034\022\034\026\037\027\042\030\035\031" +
    "\032\032\041\033\036\051\030\052\040\053\044\055\031" +
    "\056\033\057\027\001\002\000\034\022\034\026\037\027" +
    "\042\030\035\031\032\032\041\033\036\051\030\052\040" +
    "\053\044\055\031\056\033\057\027\001\002\000\016\023" +
    "\ufff1\034\052\035\051\036\054\037\047\040\053\001\002" +
    "\000\016\023\uffef\034\052\035\051\036\054\037\047\040" +
    "\053\001\002\000\016\023\ufff0\034\052\035\051\036\054" +
    "\037\047\040\053\001\002\000\016\023\ufff2\034\052\035" +
    "\051\036\054\037\047\040\053\001\002\000\034\022\034" +
    "\026\122\027\042\030\035\031\032\032\124\033\123\051" +
    "\030\052\040\053\044\055\031\056\033\057\027\001\002" +
    "\000\004\023\145\001\002\000\004\024\146\001\002\000" +
    "\020\004\020\005\023\006\016\007\017\010\012\012\013" +
    "\026\022\001\002\000\022\004\020\005\023\006\016\007" +
    "\017\010\012\012\013\025\150\026\022\001\002\000\022" +
    "\004\ufff4\005\ufff4\006\ufff4\007\ufff4\010\ufff4\012\ufff4\025" +
    "\ufff4\026\ufff4\001\002\000\004\002\001\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\147\000\004\002\003\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\010\003\020\004\013\007\014\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\006\004\111\007\014\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\005\042\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\005\065\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\005\045\001\001\000\002\001\001\000\004\005\060\001" +
    "\001\000\002\001\001\000\004\005\057\001\001\000\004" +
    "\005\056\001\001\000\004\005\055\001\001\000\004\005" +
    "\054\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\005\063\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\005" +
    "\070\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\005\073\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\005\076\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\005\101\001\001\000\002\001\001\000\004\005" +
    "\103\001\001\000\002\001\001\000\004\005\105\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\005\116\001\001\000" +
    "\002\001\001\000\002\001\001\000\006\005\124\006\125" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\010\003\130\004\013\007\014\001\001\000\006\004" +
    "\111\007\014\001\001\000\002\001\001\000\004\005\141" +
    "\001\001\000\004\005\140\001\001\000\004\005\137\001" +
    "\001\000\004\005\136\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\006\005" +
    "\124\006\143\001\001\000\002\001\001\000\002\001\001" +
    "\000\010\003\146\004\013\007\014\001\001\000\006\004" +
    "\111\007\014\001\001\000\002\001\001\000\002\001\001" +
    "" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Sintax$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Sintax$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Sintax$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    public static TablaSimbolos tabla = new TablaSimbolos();
    public static GestorTripletas gestor = new GestorTripletas();
    private Symbol s;
    public void syntax_error(Symbol s){ this.s = s; }
    public Symbol getS(){ return this.s; }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$Sintax$actions {


    private String obtenerTipo(Object o){
        if (o instanceof Integer) return "int";
        if (o instanceof Double)  return "double";
        if (o instanceof String)  return "string";
        if (o instanceof Boolean) return "boolean";
        return "null";
    }

  private final Sintax parser;

  /** Constructor */
  CUP$Sintax$actions(Sintax parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$Sintax$do_action_part00000000(
    int                        CUP$Sintax$act_num,
    java_cup.runtime.lr_parser CUP$Sintax$parser,
    java.util.Stack            CUP$Sintax$stack,
    int                        CUP$Sintax$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Sintax$result;

      /* select the action based on the action number */
      switch (CUP$Sintax$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= INICIO EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).value;
		RESULT = start_val;
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Sintax$parser.done_parsing();
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // INICIO ::= Int Main ParParentesis_a ParParentesis_c Llave_a SENTENCIA Llave_c 
            {
              Object RESULT =null;
		 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("INICIO",0, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-6)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // SENTENCIA ::= SENTENCIA DECLARACION 
            {
              Object RESULT =null;
		 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA",1, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // SENTENCIA ::= DECLARACION 
            {
              Object RESULT =null;
		 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA",1, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // TIPO_DATO ::= Int 
            {
              String RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).right;
		Object t = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.peek()).value;
		 RESULT = "int"; 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("TIPO_DATO",5, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // TIPO_DATO ::= Double 
            {
              String RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).right;
		Object t = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.peek()).value;
		 RESULT = "double"; 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("TIPO_DATO",5, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // TIPO_DATO ::= Cadena 
            {
              String RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).right;
		Object t = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.peek()).value;
		 RESULT = "string"; 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("TIPO_DATO",5, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // TIPO_DATO ::= Boolean 
            {
              String RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).right;
		Object t = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.peek()).value;
		 RESULT = "boolean"; 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("TIPO_DATO",5, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // DECLARACION ::= TIPO_DATO Identificador P_coma 
            {
              Object RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).right;
		String t = (String)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).value;
		
        if(tabla.buscar((String)id) == null) {
            tabla.insertar((String)id, (String)t);
            gestor.agregarDeclaracion((String)t, (String)id);
            System.out.println("Variable " + id + " declarada como " + t);
        } else {
            System.err.println("Error: Variable " + id + " ya existe.");
        }
    
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("DECLARACION",2, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // DECLARACION ::= TIPO_DATO Identificador Igual EXPRESION P_coma 
            {
              Object RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-4)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-4)).right;
		String t = (String)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-4)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).value;
		
        if(tabla.buscar((String)id) == null) {
            String tipoVal = obtenerTipo(e);
            if (t.equals(tipoVal) || (t.equals("double") && tipoVal.equals("int"))) {
                Simbolo s = tabla.insertar((String)id, (String)t);
                if (t.equals("double") && tipoVal.equals("int")) 
                    s.valor = Double.valueOf(e.toString());
                else 
                    s.valor = e;

                gestor.agregarDeclaracion((String)t, (String)id);
                gestor.agregarAsignacion((String)id, e.toString());

                System.out.println(t + " " + id + " = " + s.valor);
            } else {
                System.err.println("Error: No puedes asignar " + tipoVal + " a " + t);
            }
        } else {
            System.err.println("Error: Variable " + id + " ya existe.");
        }
    
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("DECLARACION",2, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-4)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // DECLARACION ::= Identificador Igual EXPRESION P_coma 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).value;
		
        Simbolo s = tabla.buscar((String)id);
        if (s != null) {
            String tipoVal = obtenerTipo(e);
            if (s.tipo.equals(tipoVal) || (s.tipo.equals("double") && tipoVal.equals("int"))) {
                if (s.tipo.equals("double") && tipoVal.equals("int")) 
                    s.valor = Double.valueOf(e.toString());
                else 
                    s.valor = e;

                gestor.agregarAsignacion((String)id, e.toString());
                System.out.println("Asignación: " + id + " = " + s.valor);
            } else {
                System.err.println("Error: Tipo incorrecto para " + id);
            }
        } else {
            System.err.println("Error: Variable " + id + " no existe.");
        }
    
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("DECLARACION",2, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // DECLARACION ::= Identificador Incremento P_coma 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).value;
		
        Simbolo s = tabla.buscar((String)id);
        if (s != null && (s.tipo.equals("int") || s.tipo.equals("double"))) {
            if(s.tipo.equals("int")) s.valor = (Integer)s.valor + 1;
            else s.valor = (Double)s.valor + 1.0;
            gestor.agregarUnaria("++", (String)id, (String)id);
            System.out.println(id + " incrementado a " + s.valor);
        } else System.err.println("Error: No se puede incrementar " + id);
    
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("DECLARACION",2, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // DECLARACION ::= Identificador Decremento P_coma 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).value;
		
        Simbolo s = tabla.buscar((String)id);
        if (s != null && (s.tipo.equals("int") || s.tipo.equals("double"))) {
            if(s.tipo.equals("int")) s.valor = (Integer)s.valor - 1;
            else s.valor = (Double)s.valor - 1.0;
            gestor.agregarUnaria("--", (String)id, (String)id);
            System.out.println(id + " decrementado a " + s.valor);
        } else System.err.println("Error: No se puede decrementar " + id);
    
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("DECLARACION",2, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // DECLARACION ::= If ParParentesis_a CONDICION ParParentesis_c Llave_a SENTENCIA Llave_c 
            {
              Object RESULT =null;
		int condleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-4)).left;
		int condright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-4)).right;
		Object cond = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-4)).value;
		
        System.out.println("If ejecutado con condición: " + cond);
    
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("DECLARACION",2, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-6)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // DECLARACION ::= While ParParentesis_a CONDICION ParParentesis_c Llave_a SENTENCIA Llave_c 
            {
              Object RESULT =null;
		int condleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-4)).left;
		int condright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-4)).right;
		Object cond = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-4)).value;
		
        System.out.println("While definido con condición: " + cond);
    
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("DECLARACION",2, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-6)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // CONDICION ::= EXPRESION IgualIgual EXPRESION 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.peek()).value;
		 RESULT = e1.equals(e2); 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("CONDICION",4, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // CONDICION ::= EXPRESION Diferente EXPRESION 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.peek()).value;
		 RESULT = !e1.equals(e2); 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("CONDICION",4, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // CONDICION ::= EXPRESION Menor EXPRESION 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.peek()).value;
		 
                  double v1 = Double.parseDouble(e1.toString());
                  double v2 = Double.parseDouble(e2.toString());
                  RESULT = v1 < v2; 
              
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("CONDICION",4, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // CONDICION ::= EXPRESION Mayor EXPRESION 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.peek()).value;
		 
                  double v1 = Double.parseDouble(e1.toString());
                  double v2 = Double.parseDouble(e2.toString());
                  RESULT = v1 > v2; 
              
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("CONDICION",4, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // CONDICION ::= True 
            {
              Object RESULT =null;
		 RESULT = true; 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("CONDICION",4, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // CONDICION ::= False 
            {
              Object RESULT =null;
		 RESULT = false; 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("CONDICION",4, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // CONDICION ::= Identificador 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.peek()).value;
		 
                  Simbolo s = tabla.buscar((String)id);
                  RESULT = (s != null && s.tipo.equals("boolean")) ? s.valor : false;
              
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("CONDICION",4, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // EXPRESION ::= EXPRESION Suma EXPRESION 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.peek()).value;
		
        String t1 = obtenerTipo(e1), t2 = obtenerTipo(e2);
        if (t1.equals("string") || t2.equals("string")) {
            RESULT = e1.toString() + e2.toString();
        } else if (t1.equals("double") || t2.equals("double")) {
            RESULT = Double.parseDouble(e1.toString()) + Double.parseDouble(e2.toString());
        } else if (t1.equals("int") && t2.equals("int")) {
            RESULT = (int)e1 + (int)e2;
        } else RESULT = null;
        gestor.agregarTripleta("+", e1.toString(), e2.toString());
    
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("EXPRESION",3, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // EXPRESION ::= EXPRESION Resta EXPRESION 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.peek()).value;
		
        String t1 = obtenerTipo(e1), t2 = obtenerTipo(e2);
        if (t1.equals("double") || t2.equals("double")) {
            RESULT = Double.parseDouble(e1.toString()) - Double.parseDouble(e2.toString());
        } else if (t1.equals("int") && t2.equals("int")) {
            RESULT = (int)e1 - (int)e2;
        } else RESULT = null;
        gestor.agregarTripleta("-", e1.toString(), e2.toString());
    
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("EXPRESION",3, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // EXPRESION ::= EXPRESION Multiplicacion EXPRESION 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.peek()).value;
		
        String t1 = obtenerTipo(e1), t2 = obtenerTipo(e2);
        if (t1.equals("double") || t2.equals("double")) {
            RESULT = Double.parseDouble(e1.toString()) * Double.parseDouble(e2.toString());
        } else if (t1.equals("int") && t2.equals("int")) {
            RESULT = (int)e1 * (int)e2;
        } else RESULT = null;
        gestor.agregarTripleta("*", e1.toString(), e2.toString());
    
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("EXPRESION",3, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // EXPRESION ::= EXPRESION Division EXPRESION 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.peek()).value;
		
        String t1 = obtenerTipo(e1), t2 = obtenerTipo(e2);
        double divisor = Double.parseDouble(e2.toString());
        if (divisor == 0) {
            System.err.println("Error: División por cero");
            RESULT = null;
        } else if (t1.equals("double") || t2.equals("double")) {
            RESULT = Double.parseDouble(e1.toString()) / divisor;
        } else if (t1.equals("int") && t2.equals("int")) {
            RESULT = (int)e1 / (int)e2;
        } else RESULT = null;
        gestor.agregarTripleta("/", e1.toString(), e2.toString());
    
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("EXPRESION",3, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // EXPRESION ::= EXPRESION Potencia EXPRESION 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.peek()).value;
		
        double base = Double.parseDouble(e1.toString());
        double exp = Double.parseDouble(e2.toString());
        double res = Math.pow(base, exp);
        if (res % 1 == 0) RESULT = (int)res;
        else RESULT = res;
        gestor.agregarTripleta("^", e1.toString(), e2.toString());
    
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("EXPRESION",3, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // EXPRESION ::= Sqrt ParParentesis_a EXPRESION ParParentesis_c 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).value;
		
        double val = Double.parseDouble(e.toString());
        if (val < 0) {
            System.err.println("Error: sqrt de número negativo");
            RESULT = null;
        } else {
            RESULT = Math.sqrt(val);
            gestor.agregarTripleta("sqrt", e.toString(), "-");
        }
    
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("EXPRESION",3, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // EXPRESION ::= Sin ParParentesis_a EXPRESION ParParentesis_c 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).value;
		
        double x = Double.parseDouble(e.toString());
        String temp = gestor.agregarSinTaylor(x, 10);
        RESULT = FuncionesMatematicas.sinTaylor(x, 10);
        System.out.println("sin(" + x + ") ≈ " + RESULT + " [" + temp + "]");
    
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("EXPRESION",3, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // EXPRESION ::= Cos ParParentesis_a EXPRESION ParParentesis_c 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).value;
		
        double x = Double.parseDouble(e.toString());
        String temp = gestor.agregarCosTaylor(x, 10);
        RESULT = FuncionesMatematicas.cosTaylor(x, 10);
        System.out.println("cos(" + x + ") ≈ " + RESULT + " [" + temp + "]");
    
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("EXPRESION",3, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // EXPRESION ::= Factorial ParParentesis_a EXPRESION ParParentesis_c 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).value;
		
        int n = Integer.parseInt(e.toString());
        if (n < 0) {
            System.err.println("Error: factorial de número negativo");
            RESULT = null;
        } else {
            String temp = gestor.agregarFactorial(n);
            RESULT = FuncionesMatematicas.factorial(n);
            System.out.println(n + "! = " + RESULT + " [" + temp + "]");
        }
    
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("EXPRESION",3, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // EXPRESION ::= Fibonacci ParParentesis_a EXPRESION ParParentesis_c 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).value;
		
        int n = Integer.parseInt(e.toString());
        if (n < 0) {
            System.err.println("Error: fibonacci de número negativo");
            RESULT = null;
        } else {
            String temp = gestor.agregarFibonacci(n);
            RESULT = FuncionesMatematicas.fibonacci(n);
            System.out.println("fib(" + n + ") = " + RESULT + " [" + temp + "]");
        }
    
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("EXPRESION",3, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // EXPRESION ::= FormulaGeneral ParParentesis_a EXPRESION Coma EXPRESION Coma EXPRESION ParParentesis_c 
            {
              Object RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-5)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-5)).right;
		Object a = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-5)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)).right;
		Object b = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).right;
		Object c = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).value;
		
        double aVal = Double.parseDouble(a.toString());
        double bVal = Double.parseDouble(b.toString());
        double cVal = Double.parseDouble(c.toString());
        
        String temp = gestor.agregarFormulaGeneral(aVal, bVal, cVal);
        double[] raices = FuncionesMatematicas.formulaGeneral(aVal, bVal, cVal);
        
        if (raices == null) {
            System.out.println("No hay raíces reales");
            RESULT = "Sin raíces reales";
        } else if (raices.length == 1) {
            System.out.println("Raíz única: x = " + raices[0] + " [" + temp + "]");
            RESULT = raices[0];
        } else {
            System.out.println("x1 = " + raices[0] + ", x2 = " + raices[1] + " [tripletas generadas]");
            RESULT = "x1=" + raices[0] + ", x2=" + raices[1];
        }
    
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("EXPRESION",3, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-7)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // EXPRESION ::= Numero 
            {
              Object RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).right;
		Object n = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.peek()).value;
		 RESULT = Integer.parseInt((String)n); 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("EXPRESION",3, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // EXPRESION ::= NumeroDecimal 
            {
              Object RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).right;
		Object n = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.peek()).value;
		 RESULT = Double.parseDouble((String)n); 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("EXPRESION",3, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // EXPRESION ::= CadenaLiteral 
            {
              Object RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).right;
		Object s = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.peek()).value;
		 RESULT = (String)s; 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("EXPRESION",3, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // EXPRESION ::= True 
            {
              Object RESULT =null;
		 RESULT = true; 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("EXPRESION",3, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // EXPRESION ::= False 
            {
              Object RESULT =null;
		 RESULT = false; 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("EXPRESION",3, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // EXPRESION ::= Identificador 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.peek()).value;
		 
        Simbolo s = tabla.buscar((String)id); 
        RESULT = (s != null) ? s.valor : null; 
    
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("EXPRESION",3, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // EXPRESION ::= ParParentesis_a EXPRESION ParParentesis_c 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).value;
		 RESULT = e; 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("EXPRESION",3, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$Sintax$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$Sintax$do_action(
    int                        CUP$Sintax$act_num,
    java_cup.runtime.lr_parser CUP$Sintax$parser,
    java.util.Stack            CUP$Sintax$stack,
    int                        CUP$Sintax$top)
    throws java.lang.Exception
    {
              return CUP$Sintax$do_action_part00000000(
                               CUP$Sintax$act_num,
                               CUP$Sintax$parser,
                               CUP$Sintax$stack,
                               CUP$Sintax$top);
    }
}

}
