
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Factorial = 43;
  public static final int True = 24;
  public static final int Incremento = 31;
  public static final int ParParentesis_c = 17;
  public static final int Coma = 15;
  public static final int ParParentesis_a = 16;
  public static final int Double = 3;
  public static final int Llave_c = 19;
  public static final int Llave_a = 18;
  public static final int If = 6;
  public static final int IgualIgual = 33;
  public static final int Diferente = 34;
  public static final int Potencia = 30;
  public static final int Decremento = 32;
  public static final int Menor = 35;
  public static final int Else = 7;
  public static final int Mayor = 36;
  public static final int Return = 11;
  public static final int Fibonacci = 44;
  public static final int While = 8;
  public static final int CadenaLiteral = 23;
  public static final int Division = 29;
  public static final int NumeroDecimal = 22;
  public static final int Int = 2;
  public static final int FormulaGeneral = 45;
  public static final int Cadena = 4;
  public static final int Tan = 42;
  public static final int For = 9;
  public static final int EOF = 0;
  public static final int P_coma = 12;
  public static final int error = 1;
  public static final int Sqrt = 39;
  public static final int False = 25;
  public static final int ERROR = 14;
  public static final int MenorIgual = 37;
  public static final int Identificador = 20;
  public static final int Cos = 41;
  public static final int Resta = 27;
  public static final int MayorIgual = 38;
  public static final int Boolean = 5;
  public static final int Multiplicacion = 28;
  public static final int Numero = 21;
  public static final int Suma = 26;
  public static final int Main = 10;
  public static final int Sin = 40;
  public static final int Igual = 13;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "Int",
  "Double",
  "Cadena",
  "Boolean",
  "If",
  "Else",
  "While",
  "For",
  "Main",
  "Return",
  "P_coma",
  "Igual",
  "ERROR",
  "Coma",
  "ParParentesis_a",
  "ParParentesis_c",
  "Llave_a",
  "Llave_c",
  "Identificador",
  "Numero",
  "NumeroDecimal",
  "CadenaLiteral",
  "True",
  "False",
  "Suma",
  "Resta",
  "Multiplicacion",
  "Division",
  "Potencia",
  "Incremento",
  "Decremento",
  "IgualIgual",
  "Diferente",
  "Menor",
  "Mayor",
  "MenorIgual",
  "MayorIgual",
  "Sqrt",
  "Sin",
  "Cos",
  "Tan",
  "Factorial",
  "Fibonacci",
  "FormulaGeneral"
  };
}

